"""Parse GraphViz dot files exported from GRAMPS."""

import re
from pathlib import Path

from family_chart.family import Family
from family_chart.graph_settings import GraphSettings
from family_chart.person import Person
from family_chart.relationship import Relationship
from family_chart.text_line import TextLine

_NODE_RE = re.compile(r'"([IF]\w+)"\s*\[(.+)\]\s*;')
_REL_RE = re.compile(r'"(\w+)"\s*->\s*"(\w+)"\s*\[([^\]]+)\]')
_ATTR_KV_RE = re.compile(r'(\w+)=(?:"([^"]*)"|(\S+?)(?=\s|$|\]))')
_META_STAT_RE = re.compile(r"#\s+(.+?):\s+(\d+)")
_META_POI_RE = re.compile(r"#\s+->\s+(\w+),\s+(.+)")
_TOPLEVEL_ATTR_RE = re.compile(r'^(\w+)=(?:"([^"]+)"|(\S+?))\s*;')
_ATTR_BLOCK_RE = re.compile(r"^(\w+)\s*\[([^\]]+)\]\s*;")
_TD_RE = re.compile(r"<TD([^>]*)>(.*?)</TD>", re.DOTALL)
_HREF_RE = re.compile(r'HREF="([^"]+)"')
_IMG_RE = re.compile(r'<IMG SRC="([^"]+)"')
_FILLCOLOR_RE = re.compile(r'fillcolor="([^"]+)"')


class GvParser:
    """Parser for GraphViz files generated by Gramps."""

    def parse_attr_block(self, s: str) -> dict[str, str]:
        """Parse a line from attribute section of GraphViz graph."""
        result = {}
        for m in _ATTR_KV_RE.finditer(s):
            result[m.group(1)] = m.group(2) if m.group(2) is not None else m.group(3)
        return result

    def parse_label(self, html: str) -> tuple[str | None, list[TextLine]]:
        """Return (photo, text_lines) where the name, if present, is text_lines[0]."""
        photo = None
        text_lines: list[TextLine] = []

        for td_attrs, td_content in _TD_RE.findall(html):
            img = _IMG_RE.search(td_content)
            if img:
                photo = img.group(1)
                continue

            text = re.sub(r"<[^>]+>", "", td_content).strip()
            if not text:
                continue

            href_m = _HREF_RE.search(td_attrs)
            if 'ALIGN="LEFT"' in td_attrs or href_m:
                text_lines.append(TextLine(text=text, map_url=href_m.group(1) if href_m else None))
            else:
                text_lines.append(TextLine(text=text))

        return photo, text_lines

    def parse_header_line(self, line: str, settings: GraphSettings) -> None:
        """Parse settings attributes."""
        m = _META_STAT_RE.match(line)
        if m:
            settings.metadata[m.group(1)] = int(m.group(2))
            return
        m = _META_POI_RE.match(line)
        if m:
            settings.people_of_interest.append((m.group(1), m.group(2).strip()))
            return
        m = _ATTR_BLOCK_RE.match(line)
        if m:
            block, attrs = m.group(1), self.parse_attr_block(m.group(2))
            if block == "edge":
                settings.edge_defaults = attrs
            elif block == "node":
                settings.node_defaults = attrs
            elif block == "graph":
                settings.graph_attrs = attrs
            return
        m = _TOPLEVEL_ATTR_RE.match(line)
        if m:
            settings.attrs[m.group(1)] = m.group(2) if m.group(2) is not None else m.group(3)

    def parse_family_label(self, html: str) -> list[TextLine]:
        """Split a family TD's <BR/>-delimited content into text_lines."""
        text_lines = []
        for td_attrs, td_content in _TD_RE.findall(html):
            href_m = _HREF_RE.search(td_attrs)
            map_url = href_m.group(1) if href_m else None
            for part in re.split(r"<BR\s*/?>", td_content):
                text = re.sub(r"<[^>]+>", "", part).strip()
                if text:
                    text_lines.append(TextLine(text=text, map_url=map_url))
        return text_lines

    def get_fillcolor(self, attrs_str: str) -> str | None:
        """Extract fill color attribute."""
        m = _FILLCOLOR_RE.search(attrs_str)
        return m.group(1) if m else None

    def parse_family_node(self, node_id: str, attrs_str: str) -> Family:
        """Extract all family attribute."""
        label_m = re.search(r"label=<<(.+?)>>", attrs_str, re.DOTALL)
        label_html = label_m.group(1) if label_m else ""
        return Family(
            id=node_id, fillcolor=self.get_fillcolor(attrs_str), text_lines=self.parse_family_label(label_html)
        )

    def parse_person_node(self, node_id: str, attrs_str: str) -> Person:
        """Extract all person attributes."""
        label_m = re.search(r"label=<<(.+?)>>", attrs_str, re.DOTALL)
        label_html = label_m.group(1) if label_m else ""
        photo, text_lines = self.parse_label(label_html)
        attrs = self.parse_attr_block(attrs_str)
        raw = attrs.get("all_marriages", "")
        all_marriages = [m.strip() for m in raw.split(",") if m.strip()]
        return Person(
            id=node_id,
            fillcolor=self.get_fillcolor(attrs_str),
            photo=photo,
            text_lines=text_lines,
            all_marriages=all_marriages,
        )

    def parse(self, path: str | Path) -> tuple[GraphSettings, list[Person], list[Family], list[Relationship]]:
        """Parse a GRAMPS-exported GraphViz dot file."""
        settings = GraphSettings()
        people: list[Person] = []
        families: list[Family] = []
        relationships: list[Relationship] = []
        in_header = True

        for line in Path(path).read_text(encoding="utf-8").splitlines():
            stripped = line.strip()
            rel_m = _REL_RE.match(stripped)
            if rel_m:
                in_header = False
                relationships.append(
                    Relationship(
                        from_id=rel_m.group(1),
                        to_id=rel_m.group(2),
                        attrs=self.parse_attr_block(rel_m.group(3)),
                    )
                )
                continue
            node_m = _NODE_RE.match(stripped)
            if node_m:
                in_header = False
                node_id, attrs_str = node_m.group(1), node_m.group(2)
                if node_id.startswith("F"):
                    families.append(self.parse_family_node(node_id, attrs_str))
                else:
                    people.append(self.parse_person_node(node_id, attrs_str))
                continue
            if in_header:
                self.parse_header_line(stripped, settings)

        return settings, people, families, relationships
